### ISSUE TITLE
Validation fails with larger files

### ISSUE THREAD

**Issue by MarinusVonhof** [rdf-ext/shacl-engine#12]
Thanks for this new package, it is hard to find a fast SHACL-engine.

Maybe helpful: 
Your package (**shacl-engine**) does not validate the combination of the files in the attachment:
[shacl_test.zip](https://github.com/rdf-ext/shacl-engine/files/14167174/shacl_test.zip)

Package **rdf-vlidate-shacl** succeeds, but it takes some time (540 sec). 
The **ITB-validator** (java-based) succeeds in 97 sec.
 
In the attachment, the file data_0.ttl contains the dataset/the individuals. 
It's about 16 Mb, not large for the RDF-data I'm used to.

Hopefully this can be of help.

**Comment by bergos** [comment]
@MarinusVonhof Thanks for the example. I can reproduce the problem but haven't had time yet to debug it. I will look into it in the next few days.

**Comment by bergos** [comment]
@MarinusVonhof can you update your dependencies and try again? Make sure you are using Grapoi v1.1.2. [This PR](https://github.com/rdf-ext/grapoi/pull/15) should have solved the performance issue.

I would be curious how long it takes on your machine after the fix.
