### ISSUE TITLE
Exception during validation

### ISSUE THREAD

**Issue by MarinusVonhof** [rdf-ext/shacl-engine#13]
Maybe also helpful: 

The shacl-engine gives an error in compileOr() while validating the combined files in this attachment:
[shacl_test2.zip](https://github.com/rdf-ext/shacl-engine/files/14167336/shacl_test2.zip)
The other shacl-validators run ok.

Best regards.

**Comment by bergos** [comment]
@MarinusVonhof Thanks! It is fixed in the latest release. The problem was caused by multiple `sh:or` lists. `sh:and` and `sh:xone` had the same problem. It's also fixed for those.
