### ISSUE TITLE
Exception with unclear message

### ISSUE THREAD

**Issue by MarinusVonhof** [rdf-ext/shacl-engine#16]
Hello,
The validator throws "Cannot read properties of null (reading '0')"
Probably expecting reading an array?

The exception occurs while validating the combination of the files in the attachment:
[test shacl.zip](https://github.com/rdf-ext/shacl-engine/files/14433005/test.shacl.zip)

It runs ok when the propertyshape "gwsw_cfk:AfmetingLeiding_card" is removed.
Also it runs ok without checking on closed properties.

Hope this helps, with best regards.

**Comment by bergos** [comment]
I was able to reproduce the problem. See the PR for more details. A test was added and the bug was fixed.

Fixed in #17 released in v0.1.5

**Comment by MarinusVonhof** [comment]
Ok Thomas, thanks again!
Best regards, Marinus

Van: Thomas Bergwinkl ***@***.***>
Verzonden: woensdag 6 maart 2024 22:31
Aan: rdf-ext/shacl-engine ***@***.***>
CC: Marinus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rdf-ext/shacl-engine] Exception with unclear message (Issue #16)


I was able to reproduce the problem. See the PR for more details. A test was added and the bug was fixed.

Fixed in #17<https://github.com/rdf-ext/shacl-engine/pull/17> released in v0.1.5
