### ISSUE TITLE
Dual Packaging

### ISSUE THREAD

**Issue by jeswr** [rdf-ext/shacl-engine#36]
Would you be open to dual packaging this to make life easier for those still using CommonJS. I've encountered a few people struggling to adopt this library because of the lack of CJS support.

**Comment by bergos** [comment]
I don't want to open that door. I maintain dependencies and related packages, which would be next. And it's not about adding the "feature". It needs time to maintain it and to provide support.

As far as I know, all popular bundlers support ESM, so I guess it's a  Node.js code base. [Dynamic import](https://nodejs.org/api/esm.html#import-expressions) should work in that case. Did they try that?
